[workspace]
members = [
    ".",
    "monz0-lib",
]

[workspace.package]
edition = "2024"
rust-version = "1.85.0"
license = "MIT"

[workspace.lints.rust]
missing_docs = "deny"
missing_debug_implementations = "deny"
missing_copy_implementations = "deny"

[workspace.lints.clippy]
all = "deny"
pedantic = "warn"
nursery = "warn"

[package]
name = "monz0"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0.52"
confy = "2.0.0"
monz0-lib = { version = "0.1.0", path = "./monz0-lib" }
rusty-money = { version = "0.4.1", features = ["iso"] }
tokio = { version = "1.16.0", features = ["rt-multi-thread", "macros", "sync"] }
tracing = "0.1.29"
tracing-subscriber = { version = "0.3.5", features = ["env-filter"] }
serde = { version = "1.0.133", features = ["derive"] }
indexmap = "1.8.0"

[dev-dependencies]
toml = "0.9"
